// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;

using Foundation;
using AppKit;
using Tunez;

namespace MacTunez
{
	public partial class SelectServerViewController : NSViewController
	{
		public event EventHandler<ServerDetails> ServerSelected;

		public SelectServerViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			AddServerButton.Activated += (sender, e) => {
				SelectAndSave (new ServerDetails {
					ManuallyEntered = true,
					Hostname = ServerAddressTextField.StringValue,
					Port = int.Parse (PortTextField.StringValue)
				});
			};

			ServerBrowser.ServerSelected += (sender, e) => {
				SelectAndSave (e);
			};
		}

		void SelectAndSave (ServerDetails server)
		{
			var knownServers = Caches.LoadKnownServers ().ToList ();
			foreach (var v in knownServers)
				v.Default = false;

			var existing = knownServers.IndexOf (server);
			if (existing == -1)
				knownServers.Add (server);
			else
				server = knownServers [existing];

			Caches.SaveKnownServers (knownServers.ToArray ());
			ServerSelected?.Invoke (this, knownServers.Last ());
		}
	}
}
